buildscript {
    ext.versions = [
            minSdk: 26,
            targetSdk: 34,
            compileSdk: 36,
            versionCode: 11,
            versionName: '1.6.0',

            jvmTarget: '17',
            sourceCompatibility: JavaVersion.VERSION_17,
            targetCompatibility: JavaVersion.VERSION_17,
            hilt: '2.57.2'
    ]
    ext.boms = [
            compose: 'androidx.compose:compose-bom:2024.01.00'
    ]

    dependencies {

    }
    repositories {
        google()
    }
}

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '8.13.2' apply false
    id 'com.android.library' version '8.13.2' apply false
    id "com.google.dagger.hilt.android" version "2.57.2" apply false
    id 'org.jetbrains.kotlin.android' version '2.4.10' apply false
    id 'org.jetbrains.kotlin.jvm' version '2.4.10' apply false
    id 'org.jetbrains.kotlin.plugin.compose' version '2.4.10' apply false
    id 'com.google.devtools.ksp' version "2.3.10" apply false
    id 'androidx.room' version "2.8.4" apply false
}

subprojects {
    configurations.configureEach {
        resolutionStrategy.force 'org.jetbrains.kotlin:kotlin-metadata-jvm:2.4.10'
    }
    plugins.withId('com.android.application') {
        dependencies.add('testImplementation', 'junit:junit:4.13.2')
    }
    plugins.withId('com.android.library') {
        dependencies.add('testImplementation', 'junit:junit:4.13.2')
    }
}
